function createfigure(feval_acc_common_elements, accuracy_mean_seq)
%CREATEFIGURE(feval_acc_common_elements, accuracy_mean_seq)
%  FEVAL_ACC_COMMON_ELEMENTS:  vector of x data
%  ACCURACY_MEAN_SEQ:  vector of y data

%  Auto-generated by MATLAB on 30-Apr-2018 16:51:03

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create loglog
loglog(feval_acc_common_elements,accuracy_mean_seq,...
    'DisplayName','accuracy_mean_seq vs feval_acc_common_elements');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XMinorTick','on','XScale','log','YMinorTick','on','YScale','log');

% 2nd version
% 3rd version